export const VERA_PAY_ABI = [
  {
    type: "constructor",
    inputs: [
      { name: "_feeRecipient", type: "address" },
      { name: "_feeBps", type: "uint256" },
    ],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "createPlan",
    inputs: [
      { name: "_paymentToken", type: "address" },
      { name: "_amount", type: "uint256" },
      { name: "_interval", type: "uint256" },
      { name: "_name", type: "string" },
      { name: "_metadataURI", type: "string" },
    ],
    outputs: [{ name: "planId", type: "uint256" }],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "togglePlan",
    inputs: [{ name: "_planId", type: "uint256" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "subscribe",
    inputs: [{ name: "_planId", type: "uint256" }],
    outputs: [{ name: "subId", type: "uint256" }],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "cancelSubscription",
    inputs: [{ name: "_subId", type: "uint256" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "processPayment",
    inputs: [{ name: "_subId", type: "uint256" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "batchProcessPayments",
    inputs: [{ name: "_subIds", type: "uint256[]" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "getPlan",
    inputs: [{ name: "_planId", type: "uint256" }],
    outputs: [
      {
        name: "",
        type: "tuple",
        components: [
          { name: "merchant", type: "address" },
          { name: "paymentToken", type: "address" },
          { name: "amount", type: "uint256" },
          { name: "interval", type: "uint256" },
          { name: "name", type: "string" },
          { name: "metadataURI", type: "string" },
          { name: "active", type: "bool" },
        ],
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getSubscription",
    inputs: [{ name: "_subId", type: "uint256" }],
    outputs: [
      {
        name: "",
        type: "tuple",
        components: [
          { name: "planId", type: "uint256" },
          { name: "subscriber", type: "address" },
          { name: "startTime", type: "uint256" },
          { name: "lastPaymentTime", type: "uint256" },
          { name: "paymentsCount", type: "uint256" },
          { name: "active", type: "bool" },
        ],
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getMerchantPlans",
    inputs: [{ name: "_merchant", type: "address" }],
    outputs: [{ name: "", type: "uint256[]" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getSubscriberSubscriptions",
    inputs: [{ name: "_subscriber", type: "address" }],
    outputs: [{ name: "", type: "uint256[]" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "isPaymentDue",
    inputs: [{ name: "_subId", type: "uint256" }],
    outputs: [{ name: "", type: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getDuePayments",
    inputs: [{ name: "_subIds", type: "uint256[]" }],
    outputs: [{ name: "due", type: "uint256[]" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "nextPlanId",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "nextSubscriptionId",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "protocolFeeBps",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "activeSub",
    inputs: [
      { name: "planId", type: "uint256" },
      { name: "subscriber", type: "address" },
    ],
    outputs: [{ name: "subId", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "event",
    name: "PlanCreated",
    inputs: [
      { name: "planId", type: "uint256", indexed: true },
      { name: "merchant", type: "address", indexed: true },
      { name: "paymentToken", type: "address", indexed: false },
      { name: "amount", type: "uint256", indexed: false },
      { name: "interval", type: "uint256", indexed: false },
      { name: "name", type: "string", indexed: false },
      { name: "metadataURI", type: "string", indexed: false },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "PlanToggled",
    inputs: [
      { name: "planId", type: "uint256", indexed: true },
      { name: "active", type: "bool", indexed: false },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "Subscribed",
    inputs: [
      { name: "subscriptionId", type: "uint256", indexed: true },
      { name: "planId", type: "uint256", indexed: true },
      { name: "subscriber", type: "address", indexed: true },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "PaymentProcessed",
    inputs: [
      { name: "subscriptionId", type: "uint256", indexed: true },
      { name: "planId", type: "uint256", indexed: true },
      { name: "subscriber", type: "address", indexed: true },
      { name: "merchant", type: "address", indexed: false },
      { name: "amount", type: "uint256", indexed: false },
      { name: "protocolFee", type: "uint256", indexed: false },
      { name: "timestamp", type: "uint256", indexed: false },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "SubscriptionCancelled",
    inputs: [
      { name: "subscriptionId", type: "uint256", indexed: true },
      { name: "subscriber", type: "address", indexed: true },
    ],
    anonymous: false,
  },
] as const;

export const ERC20_ABI = [
  {
    type: "function",
    name: "approve",
    inputs: [
      { name: "spender", type: "address" },
      { name: "amount", type: "uint256" },
    ],
    outputs: [{ name: "", type: "bool" }],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "allowance",
    inputs: [
      { name: "owner", type: "address" },
      { name: "spender", type: "address" },
    ],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "balanceOf",
    inputs: [{ name: "account", type: "address" }],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "decimals",
    inputs: [],
    outputs: [{ name: "", type: "uint8" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "symbol",
    inputs: [],
    outputs: [{ name: "", type: "string" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "mint",
    inputs: [
      { name: "to", type: "address" },
      { name: "amount", type: "uint256" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
] as const;
